--시퀀스 드랍
DROP SEQUENCE SEQ_MINI_BOARD_ID;
DROP SEQUENCE SEQ_MINI_CATEGORY_ID;
--시퀀스 생서
CREATE SEQUENCE SEQ_MINI_BOARD_ID NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_MINI_CATEGORY_ID NOCACHE NOCYCLE;
--테이블 드랍
DROP TABLE MINI_BOARD CASCADE CONSTRAINTS;
DROP TABLE MINI_CATEGORY CASCADE CONSTRAINTS;
--테이블 생성
CREATE TABLE MINI_BOARD (
    NO NUMBER PRIMARY KEY
    , PARENT_NO NUMBER
    , TITLE VARCHAR(64) NOT NULL
    , CONTENT VARCHAR(2000) NOT NULL
    , CREATED_AT DATE DEFAULT SYSDATE
    , MODIFIED_AT DATE DEFAULT NULL
    , DEL_YN CHAR(1) DEFAULT 'N' CHECK(DEL_YN IN ('Y', 'N'))
    , CATEGORY_NO NUMBER NOT NULL
)
/
CREATE TABLE MINI_CATEGORY(
    CATEGORY_NO NUMBER PRIMARY KEY
    , CATEGORY_NAME VARCHAR2(64) NOT NULL
)
/

ALTER TABLE MINI_BOARD ADD CONSTRAINT FK_MINI_BOARD_TO_MINI_CATEGORY FOREIGN KEY (CATEGORY_NO) REFERENCES MINI_CATEGORY (CATEGORY_NO);
ALTER TABLE MINI_BOARD ADD CONSTRAINT FK_MINI_BOARD_PARENT  FOREIGN KEY (PARENT_NO) REFERENCES MINI_BOARD (NO);

INSERT INTO MINI_CATEGORY (CATEGORY_NO, CATEGORY_NAME) VALUES(SEQ_MINI_CATEGORY_ID.NEXTVAL, 'JAVA');
INSERT INTO MINI_CATEGORY (CATEGORY_NO, CATEGORY_NAME) VALUES(SEQ_MINI_CATEGORY_ID.NEXTVAL, 'SPRINGBOOT');
INSERT INTO MINI_CATEGORY (CATEGORY_NO, CATEGORY_NAME) VALUES(SEQ_MINI_CATEGORY_ID.NEXTVAL, 'ORACLE');
INSERT INTO MINI_CATEGORY (CATEGORY_NO, CATEGORY_NAME) VALUES(SEQ_MINI_CATEGORY_ID.NEXTVAL, 'C언어');
INSERT INTO MINI_CATEGORY (CATEGORY_NO, CATEGORY_NAME) VALUES(SEQ_MINI_CATEGORY_ID.NEXTVAL, 'C++');
INSERT INTO MINI_CATEGORY (CATEGORY_NO, CATEGORY_NAME) VALUES(SEQ_MINI_CATEGORY_ID.NEXTVAL, 'C#');
INSERT INTO MINI_CATEGORY (CATEGORY_NO, CATEGORY_NAME) VALUES(SEQ_MINI_CATEGORY_ID.NEXTVAL, 'HTML');
INSERT INTO MINI_CATEGORY (CATEGORY_NO, CATEGORY_NAME) VALUES(SEQ_MINI_CATEGORY_ID.NEXTVAL, 'JSP');
INSERT INTO MINI_CATEGORY (CATEGORY_NO, CATEGORY_NAME) VALUES(SEQ_MINI_CATEGORY_ID.NEXTVAL, 'CSS');
INSERT INTO MINI_CATEGORY (CATEGORY_NO, CATEGORY_NAME) VALUES(SEQ_MINI_CATEGORY_ID.NEXTVAL, 'JS');

COMMIT;

DECLARE
    v_id NUMBER;
    v_dummy_content VARCHAR2(2000);
    v_category_no NUMBER;
    v_category_no_seq NUMBER;
    v_parent_no NUMBER;
    v_board_ids SYS.DBMS_DEBUG_VC2COLL := SYS.DBMS_DEBUG_VC2COLL();  -- 게시글 ID 저장용
BEGIN
    v_category_no_seq := SEQ_MINI_CATEGORY_ID.CURRVAL;

    FOR i IN 1..50 LOOP
        v_id := SEQ_MINI_BOARD_ID.NEXTVAL;
        v_dummy_content := '내용 ' || v_id || DBMS_RANDOM.STRING('x', 100);
        v_category_no := MOD(i - 1, v_category_no_seq) + 1;

        -- PARENT_NO: 앞서 생성한 게시글 중 하나를 무작위 선택하거나 NULL (처음 몇 개는 부모 없음)
        IF i <= 5 THEN
            v_parent_no := NULL;  -- 초기 몇 개는 부모 없음
        ELSE
            v_parent_no := TRUNC(DBMS_RANDOM.VALUE(1, v_id));  -- 지금까지 생성된 ID 중 하나 선택
        END IF;

        INSERT INTO MINI_BOARD(NO, TITLE, CONTENT, CATEGORY_NO, PARENT_NO)
        VALUES (v_id, '제목' || v_id, v_dummy_content, v_category_no, v_parent_no);
    END LOOP;

    COMMIT;
END;
/