--시퀀스 드랍
DROP SEQUENCE SEQ_HW_BOARD_ID;
DROP SEQUENCE SEQ_HW_CATEGORY_ID;
--시퀀스 생서
CREATE SEQUENCE SEQ_HW_BOARD_ID NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_HW_CATEGORY_ID NOCACHE NOCYCLE;
--테이블 드랍
DROP TABLE HW_BOARD CASCADE CONSTRAINTS;
DROP TABLE HW_CATEGORY CASCADE CONSTRAINTS;
--테이블 생성
CREATE TABLE HW_BOARD (
    NO NUMBER PRIMARY KEY
    , TITLE VARCHAR(64) NOT NULL
    , CONTENT VARCHAR(2000) NOT NULL
    , CREATED_AT DATE DEFAULT SYSDATE
    , MODIFIED_AT DATE DEFAULT NULL
    , DEL_YN CHAR(1) DEFAULT 'N' CHECK(DEL_YN IN ('Y', 'N'))
    , CATEGORY_NO NUMBER NOT NULL
)
/
CREATE TABLE HW_CATEGORY(
    CATEGORY_NO NUMBER PRIMARY KEY
    , CATEGORY_NAME VARCHAR2(64) NOT NULL
)
/

ALTER TABLE HW_BOARD ADD CONSTRAINT FK_HW_BOARD_TO_HW_CATEGORY FOREIGN KEY (CATEGORY_NO) REFERENCES HW_CATEGORY (CATEGORY_NO);

INSERT INTO HW_CATEGORY (CATEGORY_NO, CATEGORY_NAME) VALUES(SEQ_HW_CATEGORY_ID.NEXTVAL, 'JAVA');
INSERT INTO HW_CATEGORY (CATEGORY_NO, CATEGORY_NAME) VALUES(SEQ_HW_CATEGORY_ID.NEXTVAL, 'SPRINGBOOT');
INSERT INTO HW_CATEGORY (CATEGORY_NO, CATEGORY_NAME) VALUES(SEQ_HW_CATEGORY_ID.NEXTVAL, 'ORACLE');
INSERT INTO HW_CATEGORY (CATEGORY_NO, CATEGORY_NAME) VALUES(SEQ_HW_CATEGORY_ID.NEXTVAL, 'C언어');
INSERT INTO HW_CATEGORY (CATEGORY_NO, CATEGORY_NAME) VALUES(SEQ_HW_CATEGORY_ID.NEXTVAL, 'C++');
INSERT INTO HW_CATEGORY (CATEGORY_NO, CATEGORY_NAME) VALUES(SEQ_HW_CATEGORY_ID.NEXTVAL, 'C#');
INSERT INTO HW_CATEGORY (CATEGORY_NO, CATEGORY_NAME) VALUES(SEQ_HW_CATEGORY_ID.NEXTVAL, 'HTML');
INSERT INTO HW_CATEGORY (CATEGORY_NO, CATEGORY_NAME) VALUES(SEQ_HW_CATEGORY_ID.NEXTVAL, 'JSP');
INSERT INTO HW_CATEGORY (CATEGORY_NO, CATEGORY_NAME) VALUES(SEQ_HW_CATEGORY_ID.NEXTVAL, 'CSS');
INSERT INTO HW_CATEGORY (CATEGORY_NO, CATEGORY_NAME) VALUES(SEQ_HW_CATEGORY_ID.NEXTVAL, 'JS');

COMMIT;

DECLARE
    v_id NUMBER;
    v_dummy_content VARCHAR2(2000);
    v_category_no NUMBER;
    v_category_no_seq NUMBER;
BEGIN
    v_category_no_seq := SEQ_HW_CATEGORY_ID.CURRVAL;
    FOR i IN 1..50 LOOP
        v_id := SEQ_HW_BOARD_ID.NEXTVAL;
        v_dummy_content := '내용 ' || v_id || DBMS_RANDOM.STRING('x', 100);

        v_category_no := MOD(i - 1, v_category_no_seq) + 1;

        INSERT INTO HW_BOARD(NO, TITLE, CONTENT, CATEGORY_NO)
        VALUES (v_id, '제목' || v_id, v_dummy_content, v_category_no);
    END LOOP;
    COMMIT;
END;